### ISSUE TITLE
Videos not playing on 0.84.2

### ISSUE THREAD

**Issue by leedave** [LTVA1/flipper-video-player-extra#1]
Hi there

Since the last FW update, the video player is no longer working. 
- Software starts
- Video selection shows videos correctly
- Video does not play, just shows a blank screen

**Comment by LTVA1** [comment]
Hello. I have updated source code in the main repo today to make the app work on new firmware version

**Comment by leedave** [comment]
Thank you for the update, can confirm it is working again
